spring:
  application:
    name: itoken-zuul

server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

zuul:
  routes:
    backend-admin:
      path: /backend/admin/**
      serviceId: itoken-web-admin
    backend-posts:
      path: /backend/posts/**
      serviceId: itoken-web-posts