spring:
  application:
    name: itoken-eureka

server:
  port: 8761

eureka:
  instance:
    hostname: 192.168.110.130
  client:
  #表示是否将自己注册到Eureka,因为搭建集群环境所以把自己注册到集群
    registerWithEureka: true
    #如果是单一节点 为false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.110.130:8761/eureka/,http://192.168.110.130:8861/eureka/,http://192.168.110.130:8961/eureka/