spring:
  application:
    name: itoken-service-posts
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    sentinel:
      master: mymaster
      nodes: 192.168.110.131:26379, 192.168.110.131:26380, 192.168.110.131:26381
  datasource:
    druid:
      url: jdbc:mysql://192.168.110.128:3307/itoken-service-posts?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      # MySQL 8.x: com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8602

mybatis:
  type-aliases-package: com.funtl.itoken.common.domain
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.110.130:8761/eureka/,http://192.168.110.130:8861/eureka/,http://192.168.110.130:8961/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info