spring:
  application:
    name: itoken-service-redis
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    sentinel:
      master: mymaster
      nodes: 192.168.110.131:26379, 192.168.110.131:26380, 192.168.110.131:26381

server:
  port: 8502

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.110.130:8761/eureka/,http://192.168.110.130:8861/eureka/,http://192.168.110.130:8961/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info